/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface SportsVybeInterface extends utils.Interface {
  functions: {
    "acceptChallenge(uint256,uint256,uint256)": FunctionFragment;
    "acceptMembershipTeamRequest(uint256)": FunctionFragment;
    "challengePools(uint256)": FunctionFragment;
    "checkUpkeep(bytes)": FunctionFragment;
    "createChallengePool(uint256,uint256,uint256)": FunctionFragment;
    "createTeam()": FunctionFragment;
    "delineChallenge(uint256,uint256)": FunctionFragment;
    "getChallengePoolTeamMembers(uint256)": FunctionFragment;
    "getSVTAllowance()": FunctionFragment;
    "getSVTBalance()": FunctionFragment;
    "getTeamCount(uint256)": FunctionFragment;
    "getTeamMates(uint256)": FunctionFragment;
    "getTeamSportsmanship(uint256)": FunctionFragment;
    "increaseVoteFor(uint256,uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "pending_challenge_pool_ids(uint256)": FunctionFragment;
    "performUpkeep(bytes)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "sendTeamMembershipRequest(uint256,address)": FunctionFragment;
    "sportsVybeToken()": FunctionFragment;
    "sportsmanship(address)": FunctionFragment;
    "team_membership_request(uint256,uint256)": FunctionFragment;
    "team_owner(uint256)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "votes(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptChallenge"
      | "acceptMembershipTeamRequest"
      | "challengePools"
      | "checkUpkeep"
      | "createChallengePool"
      | "createTeam"
      | "delineChallenge"
      | "getChallengePoolTeamMembers"
      | "getSVTAllowance"
      | "getSVTBalance"
      | "getTeamCount"
      | "getTeamMates"
      | "getTeamSportsmanship"
      | "increaseVoteFor"
      | "owner"
      | "pending_challenge_pool_ids"
      | "performUpkeep"
      | "renounceOwnership"
      | "sendTeamMembershipRequest"
      | "sportsVybeToken"
      | "sportsmanship"
      | "team_membership_request"
      | "team_owner"
      | "transferOwnership"
      | "votes"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptChallenge",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptMembershipTeamRequest",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "challengePools",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "checkUpkeep",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "createChallengePool",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createTeam",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "delineChallenge",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getChallengePoolTeamMembers",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSVTAllowance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSVTBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTeamCount",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTeamMates",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTeamSportsmanship",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseVoteFor",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pending_challenge_pool_ids",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "performUpkeep",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendTeamMembershipRequest",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "sportsVybeToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sportsmanship",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "team_membership_request",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "team_owner",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "votes",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptMembershipTeamRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengePools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createChallengePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createTeam", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "delineChallenge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChallengePoolTeamMembers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSVTAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSVTBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTeamCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTeamMates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTeamSportsmanship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseVoteFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pending_challenge_pool_ids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendTeamMembershipRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sportsVybeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sportsmanship",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "team_membership_request",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "team_owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "votes", data: BytesLike): Result;

  events: {
    "ChallengePoolClosed(uint256)": EventFragment;
    "ChallengePoolCreated(uint256,uint256,uint256,uint256)": EventFragment;
    "DidNotShowUp(uint256,uint256)": EventFragment;
    "EventCreated(uint256,uint256,uint256)": EventFragment;
    "Lose(uint256,uint256)": EventFragment;
    "MembershipRequestSent(uint256)": EventFragment;
    "NewTeamMate(uint256,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "TeamCreated(uint256)": EventFragment;
    "Tie(uint256,uint256)": EventFragment;
    "VoteSubmit(address,uint256,uint256)": EventFragment;
    "Win(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ChallengePoolClosed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ChallengePoolCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DidNotShowUp"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EventCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Lose"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MembershipRequestSent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewTeamMate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TeamCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Tie"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VoteSubmit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Win"): EventFragment;
}

export interface ChallengePoolClosedEventObject {
  challenge_id: BigNumber;
}
export type ChallengePoolClosedEvent = TypedEvent<
  [BigNumber],
  ChallengePoolClosedEventObject
>;

export type ChallengePoolClosedEventFilter =
  TypedEventFilter<ChallengePoolClosedEvent>;

export interface ChallengePoolCreatedEventObject {
  challenge_id: BigNumber;
  amount: BigNumber;
  team_id: BigNumber;
  challenged_team_id: BigNumber;
}
export type ChallengePoolCreatedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber, BigNumber],
  ChallengePoolCreatedEventObject
>;

export type ChallengePoolCreatedEventFilter =
  TypedEventFilter<ChallengePoolCreatedEvent>;

export interface DidNotShowUpEventObject {
  challenge_id: BigNumber;
  team_id: BigNumber;
}
export type DidNotShowUpEvent = TypedEvent<
  [BigNumber, BigNumber],
  DidNotShowUpEventObject
>;

export type DidNotShowUpEventFilter = TypedEventFilter<DidNotShowUpEvent>;

export interface EventCreatedEventObject {
  challenge_id: BigNumber;
  team1: BigNumber;
  team2: BigNumber;
}
export type EventCreatedEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  EventCreatedEventObject
>;

export type EventCreatedEventFilter = TypedEventFilter<EventCreatedEvent>;

export interface LoseEventObject {
  challenge_id: BigNumber;
  team_id: BigNumber;
}
export type LoseEvent = TypedEvent<[BigNumber, BigNumber], LoseEventObject>;

export type LoseEventFilter = TypedEventFilter<LoseEvent>;

export interface MembershipRequestSentEventObject {
  team_id: BigNumber;
}
export type MembershipRequestSentEvent = TypedEvent<
  [BigNumber],
  MembershipRequestSentEventObject
>;

export type MembershipRequestSentEventFilter =
  TypedEventFilter<MembershipRequestSentEvent>;

export interface NewTeamMateEventObject {
  team_id: BigNumber;
  user: string;
}
export type NewTeamMateEvent = TypedEvent<
  [BigNumber, string],
  NewTeamMateEventObject
>;

export type NewTeamMateEventFilter = TypedEventFilter<NewTeamMateEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface TeamCreatedEventObject {
  team_id: BigNumber;
}
export type TeamCreatedEvent = TypedEvent<[BigNumber], TeamCreatedEventObject>;

export type TeamCreatedEventFilter = TypedEventFilter<TeamCreatedEvent>;

export interface TieEventObject {
  challenge_id: BigNumber;
  team_id: BigNumber;
}
export type TieEvent = TypedEvent<[BigNumber, BigNumber], TieEventObject>;

export type TieEventFilter = TypedEventFilter<TieEvent>;

export interface VoteSubmitEventObject {
  user: string;
  challenge_id: BigNumber;
  team_id: BigNumber;
}
export type VoteSubmitEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  VoteSubmitEventObject
>;

export type VoteSubmitEventFilter = TypedEventFilter<VoteSubmitEvent>;

export interface WinEventObject {
  challenge_id: BigNumber;
  team_id: BigNumber;
}
export type WinEvent = TypedEvent<[BigNumber, BigNumber], WinEventObject>;

export type WinEventFilter = TypedEventFilter<WinEvent>;

export interface SportsVybe extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SportsVybeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptChallenge(
      challenge_id: PromiseOrValue<BigNumberish>,
      team_id: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    acceptMembershipTeamRequest(
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    challengePools(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        boolean,
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        team1: BigNumber;
        team2: BigNumber;
        amount: BigNumber;
        isAccepted: boolean;
        isClosed: boolean;
        isCompleted: boolean;
        createdAt: BigNumber;
        interval: BigNumber;
        team1_count: BigNumber;
        team2_count: BigNumber;
      }
    >;

    checkUpkeep(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string] & { upkeepNeeded: boolean; performData: string }
    >;

    createChallengePool(
      team_id: PromiseOrValue<BigNumberish>,
      challenged_team_id: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createTeam(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    delineChallenge(
      challenge_id: PromiseOrValue<BigNumberish>,
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getChallengePoolTeamMembers(
      challenge_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getSVTAllowance(overrides?: CallOverrides): Promise<[BigNumber]>;

    getSVTBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    getTeamCount(
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTeamMates(
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getTeamSportsmanship(
      _team_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    increaseVoteFor(
      challenge_id: PromiseOrValue<BigNumberish>,
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pending_challenge_pool_ids(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    performUpkeep(
      performData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sendTeamMembershipRequest(
      team_id: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sportsVybeToken(overrides?: CallOverrides): Promise<[string]>;

    sportsmanship(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    team_membership_request(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string] & { user: string }>;

    team_owner(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    votes(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { challenge_id: BigNumber }>;
  };

  acceptChallenge(
    challenge_id: PromiseOrValue<BigNumberish>,
    team_id: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  acceptMembershipTeamRequest(
    team_id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  challengePools(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      boolean,
      boolean,
      boolean,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      team1: BigNumber;
      team2: BigNumber;
      amount: BigNumber;
      isAccepted: boolean;
      isClosed: boolean;
      isCompleted: boolean;
      createdAt: BigNumber;
      interval: BigNumber;
      team1_count: BigNumber;
      team2_count: BigNumber;
    }
  >;

  checkUpkeep(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<
    [boolean, string] & { upkeepNeeded: boolean; performData: string }
  >;

  createChallengePool(
    team_id: PromiseOrValue<BigNumberish>,
    challenged_team_id: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createTeam(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  delineChallenge(
    challenge_id: PromiseOrValue<BigNumberish>,
    team_id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getChallengePoolTeamMembers(
    challenge_id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getSVTAllowance(overrides?: CallOverrides): Promise<BigNumber>;

  getSVTBalance(overrides?: CallOverrides): Promise<BigNumber>;

  getTeamCount(
    team_id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTeamMates(
    team_id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getTeamSportsmanship(
    _team_id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  increaseVoteFor(
    challenge_id: PromiseOrValue<BigNumberish>,
    team_id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  pending_challenge_pool_ids(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  performUpkeep(
    performData: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sendTeamMembershipRequest(
    team_id: PromiseOrValue<BigNumberish>,
    user: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sportsVybeToken(overrides?: CallOverrides): Promise<string>;

  sportsmanship(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  team_membership_request(
    arg0: PromiseOrValue<BigNumberish>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  team_owner(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  votes(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    acceptChallenge(
      challenge_id: PromiseOrValue<BigNumberish>,
      team_id: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    acceptMembershipTeamRequest(
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    challengePools(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        boolean,
        boolean,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        team1: BigNumber;
        team2: BigNumber;
        amount: BigNumber;
        isAccepted: boolean;
        isClosed: boolean;
        isCompleted: boolean;
        createdAt: BigNumber;
        interval: BigNumber;
        team1_count: BigNumber;
        team2_count: BigNumber;
      }
    >;

    checkUpkeep(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<
      [boolean, string] & { upkeepNeeded: boolean; performData: string }
    >;

    createChallengePool(
      team_id: PromiseOrValue<BigNumberish>,
      challenged_team_id: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createTeam(overrides?: CallOverrides): Promise<BigNumber>;

    delineChallenge(
      challenge_id: PromiseOrValue<BigNumberish>,
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getChallengePoolTeamMembers(
      challenge_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getSVTAllowance(overrides?: CallOverrides): Promise<BigNumber>;

    getSVTBalance(overrides?: CallOverrides): Promise<BigNumber>;

    getTeamCount(
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTeamMates(
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getTeamSportsmanship(
      _team_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    increaseVoteFor(
      challenge_id: PromiseOrValue<BigNumberish>,
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    pending_challenge_pool_ids(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    performUpkeep(
      performData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    sendTeamMembershipRequest(
      team_id: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    sportsVybeToken(overrides?: CallOverrides): Promise<string>;

    sportsmanship(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    team_membership_request(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    team_owner(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    votes(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "ChallengePoolClosed(uint256)"(
      challenge_id?: null
    ): ChallengePoolClosedEventFilter;
    ChallengePoolClosed(challenge_id?: null): ChallengePoolClosedEventFilter;

    "ChallengePoolCreated(uint256,uint256,uint256,uint256)"(
      challenge_id?: null,
      amount?: null,
      team_id?: null,
      challenged_team_id?: null
    ): ChallengePoolCreatedEventFilter;
    ChallengePoolCreated(
      challenge_id?: null,
      amount?: null,
      team_id?: null,
      challenged_team_id?: null
    ): ChallengePoolCreatedEventFilter;

    "DidNotShowUp(uint256,uint256)"(
      challenge_id?: null,
      team_id?: null
    ): DidNotShowUpEventFilter;
    DidNotShowUp(challenge_id?: null, team_id?: null): DidNotShowUpEventFilter;

    "EventCreated(uint256,uint256,uint256)"(
      challenge_id?: null,
      team1?: null,
      team2?: null
    ): EventCreatedEventFilter;
    EventCreated(
      challenge_id?: null,
      team1?: null,
      team2?: null
    ): EventCreatedEventFilter;

    "Lose(uint256,uint256)"(
      challenge_id?: null,
      team_id?: null
    ): LoseEventFilter;
    Lose(challenge_id?: null, team_id?: null): LoseEventFilter;

    "MembershipRequestSent(uint256)"(
      team_id?: null
    ): MembershipRequestSentEventFilter;
    MembershipRequestSent(team_id?: null): MembershipRequestSentEventFilter;

    "NewTeamMate(uint256,address)"(
      team_id?: null,
      user?: null
    ): NewTeamMateEventFilter;
    NewTeamMate(team_id?: null, user?: null): NewTeamMateEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "TeamCreated(uint256)"(team_id?: null): TeamCreatedEventFilter;
    TeamCreated(team_id?: null): TeamCreatedEventFilter;

    "Tie(uint256,uint256)"(challenge_id?: null, team_id?: null): TieEventFilter;
    Tie(challenge_id?: null, team_id?: null): TieEventFilter;

    "VoteSubmit(address,uint256,uint256)"(
      user?: null,
      challenge_id?: null,
      team_id?: null
    ): VoteSubmitEventFilter;
    VoteSubmit(
      user?: null,
      challenge_id?: null,
      team_id?: null
    ): VoteSubmitEventFilter;

    "Win(uint256,uint256)"(challenge_id?: null, team_id?: null): WinEventFilter;
    Win(challenge_id?: null, team_id?: null): WinEventFilter;
  };

  estimateGas: {
    acceptChallenge(
      challenge_id: PromiseOrValue<BigNumberish>,
      team_id: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    acceptMembershipTeamRequest(
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    challengePools(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkUpkeep(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createChallengePool(
      team_id: PromiseOrValue<BigNumberish>,
      challenged_team_id: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createTeam(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    delineChallenge(
      challenge_id: PromiseOrValue<BigNumberish>,
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getChallengePoolTeamMembers(
      challenge_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSVTAllowance(overrides?: CallOverrides): Promise<BigNumber>;

    getSVTBalance(overrides?: CallOverrides): Promise<BigNumber>;

    getTeamCount(
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTeamMates(
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTeamSportsmanship(
      _team_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    increaseVoteFor(
      challenge_id: PromiseOrValue<BigNumberish>,
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pending_challenge_pool_ids(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    performUpkeep(
      performData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sendTeamMembershipRequest(
      team_id: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sportsVybeToken(overrides?: CallOverrides): Promise<BigNumber>;

    sportsmanship(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    team_membership_request(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    team_owner(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    votes(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptChallenge(
      challenge_id: PromiseOrValue<BigNumberish>,
      team_id: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    acceptMembershipTeamRequest(
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    challengePools(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkUpkeep(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createChallengePool(
      team_id: PromiseOrValue<BigNumberish>,
      challenged_team_id: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createTeam(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    delineChallenge(
      challenge_id: PromiseOrValue<BigNumberish>,
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getChallengePoolTeamMembers(
      challenge_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSVTAllowance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSVTBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTeamCount(
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTeamMates(
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTeamSportsmanship(
      _team_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    increaseVoteFor(
      challenge_id: PromiseOrValue<BigNumberish>,
      team_id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pending_challenge_pool_ids(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    performUpkeep(
      performData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sendTeamMembershipRequest(
      team_id: PromiseOrValue<BigNumberish>,
      user: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sportsVybeToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sportsmanship(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    team_membership_request(
      arg0: PromiseOrValue<BigNumberish>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    team_owner(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    votes(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
